eureka:
    client:
        webclient:
            enabled: true
        service-url:
            defaultZone: http://discovery-service:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo/