spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.voiceprint: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
