server:
  port: 8000 # 여기로 다 받음. 그 뒤에 분배

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # Eureka에 등록된 서비스를 기반으로 자동으로 라우팅 맵을 생성
          lower-case-service-id: true # 서비스 ID를 소문자로 변환하여 URL 경로로 사용 (e.g. /backend-msa)
      server:
        webflux:
          default-filters:
            - name: GlobalLoggerFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true 
          routes:
            
            - id: notification_route
              uri: lb://notification-service  # 'lb://' 는 Eureka를 통한 로드 밸런싱 의미.
              predicates: 
                - Path=/api/notifications/**
            
            - id: backend_catch_all
              uri: lb://backend-msa
              predicates:
                - Path=/api/**

eureka:
  client:
    webclient:
      enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    