server:
  port: 8081
  forward-headers-strategy: framework
  tomcat:
    max-connections: 20000   # 목표 동접보다 여유 있게
    accept-count: 1000       # backlog 대기열 (기본 100)
spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 50   # 스레드풀 max(8) * 여유(6배)
          max-idle: 20
          min-idle: 10
          max-wait: 3000ms # 커넥션 대기 최대 3초
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      group-id: voiceprint-notification
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
  datasource: # batch 처리
    url: jdbc:mysql://${MYSQL_NOTIFICATION_HOST}:${MYSQL_NOTIFICATION_PORT}/${MYSQL_NOTIFICATION_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_NOTIFICATION_USER}
    password: ${MYSQL_NOTIFICATION_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
      # JPA batch.
      jdbc:
        batch_size: 1000           # 한 번에 전송할 레코드 수
      order_inserts: true          # 같은 테이블 insert끼리 모아서 정렬
      order_updates: true          # 같은 테이블 update끼리 모아서 정렬

  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

# 임시키
session:
  key: "dummy-session-key"
message:
  key: "dummy-message-key"

loadtest:
  token:
    secret: ${LOADTEST_TOKEN_SECRET}


# pub/sub 전용 Redis (새 인스턴스: redis-pubsub)
notification:
  redis:
    pubsub:
      host: ${REDIS_PUBSUB_HOST:redis-pubsub}
      port: 6379
      password: ${REDIS_PASSWORD}
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 10
        max-wait: 3000ms