server:
  port: 8081
  forward-headers-strategy: framework
spring:
  data:
    redis:
      host: redis
      port: 6379
      password: redis_pw123
      lettuce:
        pool:
          max-active: 50   # 스레드풀 max(8) * 여유(6배)
          max-idle: 20
          min-idle: 10
          max-wait: 3000ms # 커넥션 대기 최대 3초
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: voiceprint-notification
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
  datasource: # batch 처리
    url: jdbc:mysql://mysql_notification:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: notification_user
    password: thisisnotification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      # JPA batch.
      jdbc:
        batch_size: 1000           # 한 번에 전송할 레코드 수
      order_inserts: true          # 같은 테이블 insert끼리 모아서 정렬
      order_updates: true          # 같은 테이블 update끼리 모아서 정렬

  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

# 임시키
session:
  key: "dummy-session-key"
message:
  key: "dummy-message-key"

# pub/sub 전용 Redis (새 인스턴스: redis-pubsub)
notification:
  redis:
    pubsub:
      host: redis-pubsub   # docker-compose 에 추가할 그 이름
      port: 6379
      password: redis_pw123
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 10
        max-wait: 3000ms