server:
  port: 8081
  forward-headers-strategy: framework
spring:
  data:
    redis:
      host: redis
      port: 6379
      password: redis_pw123
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: voiceprint-notification
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
  datasource:
    url: jdbc:mysql://mysql_notification:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: notification_user
    password: thisisnotification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# 임시키
session:
  key: "dummy-session-key"
message:
  key: "dummy-message-key"
