server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    oauth2:
      resourceserver:
        jwt:
          enabled: false
security:
  basic:
    enabled: false

eureka:
  client:
    register-with-eureka: false # Eureka ??? ??? ?????? ???? ??
    fetch-registry: false       # ????? ?? ?? X