server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          url: file:///config-repo # 로컬의 config-repo 디렉토리 사용


eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/