server {
    # http로 클라이언트 요청을 수신
    listen 80;
    server_name frontend;

    # React가 빌드한 정적 파일이 위치하는 디렉토리
    root   /usr/share/nginx/html;
    # 기본 엔트리 파일
    index  index.html;

    # 싱글 페이지 애플리케이셔 라우팅 처리
    # 요청한 URI에 해당하는 파일이 있으면 서빙, 없으면 index.html 반환
    location / {
        try_files $uri $uri/ /index.html;
    }

    
    # 정적 파일 캐싱
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
      expires 14d;
      add_header Cache-Control "public";
    }
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;


}