image: gradle:8.10.0-jdk17-jammy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SONAR_HOST_URL: "$SONAR_HOST_URL"
  SONAR_TOKEN: "$SONAR_TOKEN"
stages:
  - build
  - analysis

# 빌드 단계
build:
  stage: build
  tags:
    - sonarqube
  script:
    - cd backend
    - chmod +x ./gradlew
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  
# 분석단계
analysis:
  stage: analysis
  tags:
    - sonarqube
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"

      
  script: 
    - cd backend
    - ./gradlew sonarqube \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.qualitygate.wait=true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: always
    # backend 또는 frontend 브랜치에서 develop 대상으로 MR 생성/업데이트 시
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
    # 그 외에는 실행하지 않음
    - when: never