stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
   - runner
  only:
   - develop
   - merge_requests
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    # frontend 이미지 빌드
    - docker build -t $DOCKERHUB_USER/frontend:latest frontend
    # backend 이미지 빌드
    - docker build -t $DOCKERHUB_USER/backend:latest backend
