services:
  # Frontend: Restore direct port access (81)
  frontend:
    # ports:
    #   - "${FRONTEND_PORT}:80"
    build:
      args:
        VITE_API_BASE_URL: http://localhost # 개발용
    env_file:
      - ./frontend/.env.dev
    restart: unless-stopped

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # localhost:81
    restart: unless-stopped

  kafka:
    ports:
      - "${KAFKA_PORT}:9092"
    restart: unless-stopped

  kafka-ui:
    ports:
      - "${KAFKA_UI_PORT}:8080"
    restart: unless-stopped

  discovery-service:
    ports:
      - "${DISCOVERY_SERVICE_PORT}:8761"

  config-service:
    ports:
      - "${CONFIG_SERVICE_PORT}:8888"

  gateway-service:
    ports:
      - "${GATEWAY_SERVICE_PORT}:8000"

  backend-msa:
    ports:
      - "${BACKEND_SERVICE_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  notification-service:
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  mysql:
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped

  mysql_notification:
    ports:
      - "${MYSQL_NOTIFICATION_PORT}:3306"
    restart: unless-stopped

  redis:
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  redis-pubsub:
    ports:
      - "${REDIS_PUBSUB_PORT}:6379"
    restart: unless-stopped

  mysql-notification-exporter:
    ports:
      - "${MYSQL_NOTIFICATION_EXPORTER_PORT}:9104"
    restart: unless-stopped

  mysql-exporter:
    ports:
      - "${MYSQL_EXPORTER_PORT}:9104"
    restart: unless-stopped

  redis-exporter:
    ports:
      - "${REDIS_EXPORTER_PORT}:9121"
    restart: unless-stopped

  redis-pubsub-exporter:
    ports:
      - "${REDIS_PUBSUB_EXPORTER_PORT}:9121"
    restart: unless-stopped

  prometheus:
    ports:
      - "${PROMETHEUS_PORT}:9090"

  loki:
    ports:
      - "${LOKI_PORT}:3100"
    restart: unless-stopped

  grafana:
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: unless-stopped
