services:
  frontend:
    container_name: frontend
    image: jokiheum/voiceprint-frontend:latest
    ports:
      - "81:80"
    env_file:
      - ./frontend.env
    networks:
      - voiceprint-network
  proxy:
    image: nginx:1.26-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./voiceprint.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - voiceprint-network
  backend:
    container_name: backend
    image: jokiheum/voiceprint-backend:latest
    env_file:
      - ./backend.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - voiceprint-network
    
  mysql:
    container_name: mysql
    image: jokiheum/voiceprint-mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - voiceprint-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"] # mysql이 healthy 한 지 판단
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: redis
    image: redis:8
    ports:
      - "6379:6379"
    env_file:
      - ./redis.env
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: 
      - /bin/sh
      - -c
      - redis-server /usr/local/etc/redis/redis.conf --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - voiceprint-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping"]
      interval: 5s
      retries: 10
  
volumes:
  mysql-data:
    name: mysql-data

networks:
  voiceprint-network:                
    name: voiceprint-network         
    driver: bridge