server {
  listen 80;
  server_name k12b106.p.ssafy.io;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name k12b106.p.ssafy.io;

  client_max_body_size 10m;

  # SSL 인증서 설정
  ssl_certificate /etc/letsencrypt/live/k12b106.p.ssafy.io/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/k12b106.p.ssafy.io/privkey.pem;

  # HTTPS 설정
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  location ^~ /ws {
    proxy_pass         http://backend:8080/ws;
    proxy_http_version 1.1;

    # WebSocket Upgrade 헤더
    proxy_set_header   Upgrade           $http_upgrade;
    proxy_set_header   Connection        "upgrade";

    # 전달할 헤더들
    proxy_set_header   Host              $host;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;

    # 타임아웃·버퍼링 설정
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering    off;
  }

  # sse 설정
  location ^~ /api/notifications/subscribe {
    proxy_pass        http://backend:8080;
    proxy_http_version 1.1;
    proxy_set_header  Connection "";
    proxy_set_header             Host              $host;
    proxy_set_header             X-Real-IP         $remote_addr;
    proxy_set_header             X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header             X-Forwarded-Proto $scheme;
    proxy_buffering              off;
    chunked_transfer_encoding    on;
    proxy_cache                  off;
    gzip                         off;
    proxy_read_timeout           3600s;
    proxy_send_timeout           3600s;
    send_timeout                 3600s;
  }

  # OAuth2 인가 요청
  location ~ ^/oauth2/authorization/ {
    proxy_pass http://backend:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }


  # OAuth2 콜백
  location ~ ^/login/oauth2/code/ {
    proxy_pass http://backend:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
  }

  

  # 프론트앤드 정적 파일 요청 처리
  location / {
    proxy_pass http://frontend:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # API 요청 프록시
  location ~ ^/api/ {
  proxy_pass         http://backend:8080;
  proxy_http_version 1.1;
  proxy_set_header   Upgrade           $http_upgrade;
  proxy_set_header   Connection        "upgrade";
  proxy_set_header   Host              $host;
  proxy_set_header   X-Real-IP         $remote_addr;
  proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header   X-Forwarded-Proto $scheme;

  # WebSocket 타임아웃·버퍼링 설정 (선택)
  proxy_read_timeout  3600s;
  proxy_send_timeout  3600s;
  proxy_buffering     off;
  }


}