global:
  scrape_interval: 15s      # 15초마다 데이터 스크랩
  evaluation_interval: 15s

# Alert manager 연동
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# 알람 규칙 파일
rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  # Gateway (Edge Layer)
  - job_name: 'gateway-service' # 쿼리에서 필터할 이름
    metrics_path: /actuator/prometheus  # SpringBoot Actuator가 노출하는 엔드포인트
    static_configs:
      - targets: ['gateway-service:8000']
        labels: { app: 'gateway', tier: 'edge' }

  # Backend Core Service
  - job_name: 'backend-msa'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend-msa:8080']
        labels: { app: 'core', tier: 'svc' }

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8081']
        labels: { app: 'alarm', tier: 'svc' }

  # MySQL (Notification DB Exporter)
  - job_name: 'mysql-notification'
    static_configs:
      - targets: ['mysql-notification-exporter:9104']
        labels: { db: 'notification', role: 'primary' }

  # MySQL (Main DB Exporter)
  - job_name: 'mysql-main'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels: { db: 'main', role: 'primary' }

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          db: 'redis'
          role: 'cache'

  # Redis PubSub Exporter
  - job_name: 'redis-pubsub'
    static_configs:
      - targets: ['redis-pubsub-exporter:9121']
        labels:
          db: 'redis-pubsub'
          role: 'pubsub'
