spring.application.name=voiceprint

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/voiceprint_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

#JWT
spring.jwt.secret=vmfhaltmskdlstkfkdgodyrolroqkfwkalskdjqwkjdnkasjlqsssaabbbbb

# Google registration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=840178853452-66ihn0l9l6r4uqg236d9iujedlggkvou.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=profile,email